apiVersion: v1
kind: Service
metadata:
  name: service-c
  labels:
    app: service-c
    component: service
    version: v1
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: service-c
    component: service
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  labels:
    app: service-c
    component: service
    version: v1
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-c
      component: service
      version: v1
  template:
    metadata:
      labels:
        app: service-c
        component: service
        version: v1
    spec:
      containers:
        - name: service-c
          image: registry.hub.docker.com/garystafford/go-srv-c:1.6.5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: MONGO_CONN
              valueFrom:
                secretKeyRef:
                  name: go-srv-config
                  key: mongodb.conn
          ports:
            - containerPort: 8080
          imagePullPolicy: Always