apiVersion: v1
kind: Service
metadata:
  name: service-g
  labels:
    app: service-g
    component: service
    version: "1.6.0"
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: service-g
    component: service
    version: "1.6.0"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-g
  labels:
    app: service-g
    component: service
    version: "1.6.0"
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-g
      component: service
      version: "1.6.0"
  template:
    metadata:
      labels:
        app: service-g
        component: service
        version: "1.6.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-g
        image: registry.hub.docker.com/garystafford/go-srv-g:1.6.0
        resources:
        # requests:
        #   memory: 100M
        #   cpu: 100m
        # limits:
        #   memory: 250M
        #   cpu: 250m
        env:
        - name: MONGO_CONN
          valueFrom:
            secretKeyRef:
              name: go-srv-config
              key: mongodb.conn
        - name: RABBITMQ_CONN
          valueFrom:
            secretKeyRef:
              name: go-srv-config
              key: rabbitmq.conn
        - name: SERVICE_A_URL
          value: http://service-a.dev.svc.cluster.local
        - name: SERVICE_B_URL
          value: http://service-b.dev.svc.cluster.local
        - name: SERVICE_C_URL
          value: http://service-c.dev.svc.cluster.local
        - name: SERVICE_D_URL
          value: http://service-d.dev.svc.cluster.local
        - name: SERVICE_E_URL
          value: http://service-e.dev.svc.cluster.local
        - name: SERVICE_F_URL
          value: http://service-f.dev.svc.cluster.local
        - name: SERVICE_G_URL
          value: http://service-g.dev.svc.cluster.local
        - name: SERVICE_H_URL
          value: http://service-h.dev.svc.cluster.local
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent #Always