apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-istio-observability-demo
  region: us-east-1
  version: "1.20"
vpc:
  id: vpc-05f8a5529aa3ec466
  subnets:
    public:
      us-east-1a:
        id: subnet-08960a40186489faa
      us-east-1b:
        id: subnet-0a5bf0e0aac3272da
      us-east-1c:
        id: subnet-0ed6c88868ec9e5bc
    private:
      us-east-1a:
        id: subnet-0095da84905e603d8
      us-east-1b:
        id: subnet-07a14d523a63bb502
      us-east-1c:
        id: subnet-08157483a34dd429a

iam:
  withOIDC: true
managedNodeGroups:
  - name: managed-ng-1
    amiFamily: AmazonLinux2
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 80
    labels:
      role: worker
      stack: nlp-app
    tags:
      nodegroup-name: managed-ng-1
      nodegroup-role: worker
    ssh:
      #      allow: true
      #      publicKeyPath: ~/.ssh/eks-demo-676164205626-us-east-1.pub
      enableSsm: true
    iam:
      withAddonPolicies:
        albIngress: true
        # appMesh: true
        autoScaler: true
        cloudWatch: true
# cloudWatch:
#   clusterLogging:
#     enableTypes: ["*"]
