apiVersion: v1
kind: Service
metadata:
  name: rev-proxy
  labels:
    app: rev-proxy
    component: proxy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 50051
  selector:
    app: rev-proxy
    component: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rev-proxy
  labels:
    app: rev-proxy
    component: proxy
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: rev-proxy
      component: proxy
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: rev-proxy
        component: proxy
        version: v1
    spec:
      containers:
        - name: rev-proxy
          image: {{ printf "%s/go-srv-rev-proxy:%s" .Values.image.repository .Values.image.tag.RevProxy }}
          resources:
            requests:
              memory: 125Mi
              cpu: 125m
            limits:
              memory: 400Mi
              cpu: 400m
          env:
            - name: LOG_LEVEL
              value: debug
            - name: SERVICE_A_URL
              value: service-a.dev.svc.cluster.local:50051
          ports:
            - containerPort: 50051
          imagePullPolicy: {{ .Values.image.pullPolicy }}
