apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
    component: service
spec:
  ports:
    - appProtocol: grpc
      name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: service-a
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
    component: service
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: service-a
      component: service
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: service-a
        component: service
        version: v1
    spec:
      containers:
        - name: service-a
          image: {{ printf "%s/go-srv-a:%s" .Values.image.repository .Values.image.tag.ServiceA }}
          resources:
            requests:
              memory: 125Mi
              cpu: 125m
            limits:
              memory: 400Mi
              cpu: 400m
          env:
            - name: LOG_LEVEL
              value: debug
            - name: GREETING
              value: "Howdy, from Service A!"
            - name: SERVICE_B_URL
              value: service-b.dev.svc.cluster.local:50051
            - name: SERVICE_C_URL
              value: service-c.dev.svc.cluster.local:50051
          ports:
            - containerPort: 50051
          imagePullPolicy: {{ .Values.image.pullPolicy }}
