apiVersion: v1
kind: Service
metadata:
  name: service-d
  labels:
    app: service-d
    component: service
spec:
  ports:
    - appProtocol: grpc
      name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: service-d
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  labels:
    app: service-d
    component: service
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: service-d
      component: service
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: service-d
        component: service
        version: v1
    spec:
      containers:
        - name: service-d
          image: {{ printf "%s/go-srv-d:%s" .Values.image.repository .Values.image.tag.ServiceD }}
          resources:
            requests:
              memory: 150Mi
              cpu: 250m
            limits:
              memory: 400Mi
              cpu: 600m
          env:
            - name: LOG_LEVEL
              value: info
            - name: RABBITMQ_CONN
              valueFrom:
                secretKeyRef:
                  name: go-srv-config
                  key: rabbitmq.conn
          ports:
            - containerPort: 50051
          imagePullPolicy: {{ .Values.image.pullPolicy }}
