apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
    component: service
spec:
  ports:
    - appProtocol: grpc
      name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: service-b
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
    component: service
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: service-b
      component: service
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: service-b
        component: service
        version: v1
    spec:
      containers:
        - name: service-b
          image: {{ printf "%s/go-srv-b:%s" .Values.image.repository .Values.image.tag.ServiceB }}
          resources:
            requests:
              memory: 55Mi
              cpu: 5m
            limits:
              memory: 400Mi
              cpu: 200m
          env:
            - name: LOG_LEVEL
              value: info
            - name: SERVICE_D_URL
              value: service-d.dev.svc.cluster.local:50051
            - name: SERVICE_E_URL
              value: service-e.dev.svc.cluster.local:50051
          ports:
            - containerPort: 50051
          imagePullPolicy: {{ .Values.image.pullPolicy }}
