version: '3.9'

services:
  angular-ui:
    image: garystafford/angular-observe:1.6.0
    depends_on:
      - service-a
    networks:
      - golang-demo
    ports:
      - 80:80
  service-a:
    image: garystafford/go-srv-a:1.6.0
    networks:
      - golang-demo
    ports:
      - 8000:80
    environment:
      SERVICE_B_URL: 'http://service-b'
      SERVICE_C_URL: 'http://service-c'
  service-b:
    image: garystafford/go-srv-b:1.6.0
    networks:
      - golang-demo
    environment:
      SERVICE_D_URL: 'http://service-d'
      SERVICE_E_URL: 'http://service-e'
  service-c:
    image: garystafford/go-srv-c:1.6.0
    depends_on:
      - mongodb
    networks:
      - golang-demo
    environment:
      MONGO_CONN: 'mongodb://mongodb:27017/admin'
  service-d:
    image: garystafford/go-srv-d:1.6.0
    depends_on:
      - rabbitmq
    networks:
      - golang-demo
    environment:
      RABBITMQ_CONN: 'amqp://guest:guest@rabbitmq:5672/'
  service-e:
    image: garystafford/go-srv-e:1.6.0
    networks:
      - golang-demo
    environment:
      SERVICE_G_URL: 'http://service-g'
      SERVICE_H_URL: 'http://service-h'
  service-f:
    image: garystafford/go-srv-f:1.6.0
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - golang-demo
    environment:
      RABBITMQ_CONN: 'amqp://guest:guest@rabbitmq:5672/'
      MONGO_CONN: 'mongodb://mongodb:27017/admin'
  service-g:
    image: garystafford/go-srv-g:1.6.0
    depends_on:
      - mongodb
    networks:
      - golang-demo
    environment:
      MONGO_CONN: 'mongodb://mongodb:27017/admin'
  service-h:
    image: garystafford/go-srv-h:1.6.0
    depends_on:
      - mongodb
    networks:
      - golang-demo
    environment:
      MONGO_CONN: 'mongodb://mongodb:27017/admin'
  mongodb:
    image: mongo:4.4.6
    networks:
      - golang-demo
    ports:
      - 27017:27017
  mongo_express:
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - golang-demo
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - golang-demo

networks:
  golang-demo:
    external: true

volumes:
  data: { }
