apiVersion: v1
kind: Secret
metadata:
  name: go-srv-config
  namespace: dev
type: Opaque
data:
  mongodb.conn: {{ your_base64_encoded_secret }}
  rabbitmq.conn: {{ your_base64_encoded_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-config
  namespace: mongo-express
type: Opaque
data:
  me.basicauth.username: {{ your_base64_encoded_secret }}
  me.basicauth.password: {{ your_base64_encoded_secret }}
  mongodb.host: {{ your_base64_encoded_secret }}
  mongodb.username: {{ your_base64_encoded_secret }}
  mongodb.password: {{ your_base64_encoded_secret }}